# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

matrix:
  include:
  - r: oldrel
  - r: release
  - r: release
    os: osx
    osx_image: xcode8.3
    before_install:
      - sudo tlmgr install framed titling
  - r: devel



